spring:
  ### FOR H2 DB ###
#  datasource:
#    url: jdbc:h2:mem:database
#    username: sa
#    password:
#
#  h2:
#    console:
#      enabled: true
#      path: /h2console
#
#  jpa:
#    show-sql: true
#    defer-datasource-initialization: true



  ### FOR MySQL DB ###

  datasource:
    url: jdbc:mysql://localhost:3306/utnphones
    username: root
    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    dbname: utnphones

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  logging:
    level:
      org:
        hibernate:
          SQL: debug